dist: xenial
language: shell
addons:
  apt:
    packages:
    - python3
    - python3-pip
    - python3-setuptools
before_script:
  - pip3 install --user -r test/requirements.txt
script:
  - make lint
  - make python=python3 test
